"""home2

Revision ID: 25246cb8146f
Revises: cee7bd417bd2
Create Date: 2025-12-22 02:16:16.254214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25246cb8146f'
down_revision: Union[str, Sequence[str], None] = 'cee7bd417bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    op.drop_column('users', 'alias_name')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('telegram_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('alias_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
