from models.answers import Answer
from models.questions import Question
from models.user import User
from models.appointments import Appointment
from models.base import Base
from models.consultations import Consultation
from models.logs import Log
from models.notes import Note
from models.psychologist import Psychologist
from models.results import Result
from models.tests import Test